name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your desired Node.js version
          cache: 'npm' # Or 'yarn'

      - name: Install dependencies
        run: npm install # Or yarn install

      - name: Build
        run: npm run build # Or yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # If your repository name is different from your username.github.io,
          # you might need to set the cname option:
          # cname: 'your-custom-domain.com'
          # If you are using a project page (e.g., username.github.io/repo-name)
          # and have configured `base: '/repo-name/'` in vite.config.ts,
          # you don't typically need extra configuration here for that.