name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or the branch you push your source code to

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: # <--- ADD THIS BLOCK
      contents: write # Allows the action to write to the repository (for pushing the build output)
      pages: write    # Required for deploying to GitHub Pages
      id-token: write # Required for OpenID Connect (if your action uses it)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # If your repository is sunilkumar02.github.io, you usually don't need a base path
          # because it's a user/organization page. If it were a project page (e.g., repo-name),
          # you'd need base: '/repo-name/' in vite.config.ts.
          # For sunilkumar02.github.io, your base should likely be '/' or omitted.